server:
  port: 8090

spring:
  application:
    name: User Management API

  datasource:
    url: jdbc:postgresql://localhost:5432/user-management-api
    username: postgres
    password: codeur47
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    create-schemas: true
    default-schema: user-management-api
    enabled: true
    encoding: UTF-8
    driver-class-name: org.postgresql.Driver
    locations: classpath:db/migration
    validate-on-migrate: true

logging:
  level:
    org.flywaydb: DEBUG

application:
  security:
    jwt:
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days