server:
  port: 8090

spring:
  application:
    name: User Management API

  datasource:
    url: jdbc:postgresql://localhost:5432/user-management-api
    username: postgres
    password: codeur47
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

application:
  security:
    jwt:
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days